FROM python:3.9.19

# TODO - add all the necessary to run the script populate_db.py in this image
# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script
ADD ./requirements.txt .
RUN pip install -r requirements.txt
COPY ./ /src/
WORKDIR /src
# RUN python populate_db.py
